name: sud_qollanma
description: "Sud xodimlarining kasbiy kompetentligi uchun mobil platforma."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0 # Ensure this is compatible with your Flutter version

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: # Add this for localization
    sdk: flutter         # Add this for localization

  cupertino_icons: ^1.0.8
  url_launcher: ^6.3.1 # Or latest
  provider: ^6.1.5    # Or latest
  uuid: ^4.5.1        # Or latest
  shared_preferences: ^2.5.3 # Or latest
  # Firebase Core for initializing Firebase
  firebase_core: ^4.2.1   # Or latest
  # Firebase Authentication
  firebase_auth: ^6.1.2   # Or latest
  intl: ^0.20.2
  path_provider: ^2.0.9
  # Cloud Firestore (we'll use this later for user data)
  cloud_firestore: ^6.1.0 # Or latest
  flutter_speed_dial: ^7.0.0 # Add this line

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0 # Or latest
  
flutter:
  uses-material-design: true
  generate: true # Add this line to enable code generation for localization

  assets:
    # O'ZGARISH: Yangi logotipni qo'shdim va eskisini olib tashladim
    - assets/images/app_logo.png 
    # - assets/images/Shared_Knowledge.png # Eski
    # - assets/images/Teach&Learn Logo.png # Eski
    
    # Bu rasmlar qolsin, bular shaxsiy rasmlar
    - assets/images/solijonov_madamin.jpg
    - assets/images/my_pic.jpg
